apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: equb
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/fgirmay/argocd-configuration.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: equb
syncPolicy:
  syncOptions: -CreateNamespace=true

  automated:
    selfHeal: true
    prune: true
