apiVersion: apps/v1
kind: Deployment
metadata:
  name: equb-app
  labels:
    app: equb-app
spec:
  replicas: 0
  selector:
    matchLabels:
      app: equb-app
  template:
    metadata:
      labels:
        app: equb-app
    spec:
      containers:
        - name: equb-app
          image: fissehaye/equb:1.4
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: equb-app-service
spec:
  selector:
    app: equb-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
