apiVersion: v1
kind: ConfigMap
metadata:
  name: mysqldb-configmap
data:
  database_url: mysqldb-service
  init.sql: |
    CREATE DATABASE IF NOT EXISTS equb;
    USE equb;
    CREATE TABLE User (name VARCHAR(256), username VARCHAR(256), email VARCHAR(256), password VARCHAR(256));
